//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AllotmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllotmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateOfAllotment" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AllotmentOf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Particulars" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfSecuritiesAllotted" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NominalAmountPerSecurity" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="PremiumAmountPerSecurity" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllotmentType", propOrder = {
    "dateOfAllotment",
    "allotmentOf",
    "particulars",
    "numberOfSecuritiesAllotted",
    "nominalAmountPerSecurity",
    "premiumAmountPerSecurity"
})
public class AllotmentType {

    @XmlElement(name = "DateOfAllotment", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfAllotment;
    @XmlElement(name = "AllotmentOf", required = true)
    protected String allotmentOf;
    @XmlElement(name = "Particulars", required = true)
    protected String particulars;
    @XmlElement(name = "NumberOfSecuritiesAllotted")
    protected int numberOfSecuritiesAllotted;
    @XmlElement(name = "NominalAmountPerSecurity")
    protected String nominalAmountPerSecurity;
    @XmlElement(name = "PremiumAmountPerSecurity")
    protected String premiumAmountPerSecurity;

    /**
     * Gets the value of the dateOfAllotment property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfAllotment() {
        return dateOfAllotment;
    }

    /**
     * Sets the value of the dateOfAllotment property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfAllotment(XMLGregorianCalendar value) {
        this.dateOfAllotment = value;
    }

    /**
     * Gets the value of the allotmentOf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllotmentOf() {
        return allotmentOf;
    }

    /**
     * Sets the value of the allotmentOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllotmentOf(String value) {
        this.allotmentOf = value;
    }

    /**
     * Gets the value of the particulars property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticulars() {
        return particulars;
    }

    /**
     * Sets the value of the particulars property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticulars(String value) {
        this.particulars = value;
    }

    /**
     * Gets the value of the numberOfSecuritiesAllotted property.
     * 
     */
    public int getNumberOfSecuritiesAllotted() {
        return numberOfSecuritiesAllotted;
    }

    /**
     * Sets the value of the numberOfSecuritiesAllotted property.
     * 
     */
    public void setNumberOfSecuritiesAllotted(int value) {
        this.numberOfSecuritiesAllotted = value;
    }

    /**
     * Gets the value of the nominalAmountPerSecurity property.
     * 
     */
    public String getNominalAmountPerSecurity() {
        return nominalAmountPerSecurity;
    }

    /**
     * Sets the value of the nominalAmountPerSecurity property.
     * 
     */
    public void setNominalAmountPerSecurity(String value) {
        this.nominalAmountPerSecurity = value;
    }

    /**
     * Gets the value of the premiumAmountPerSecurity property.
     * 
     */
    public String getPremiumAmountPerSecurity() {
        return premiumAmountPerSecurity;
    }

    /**
     * Sets the value of the premiumAmountPerSecurity property.
     * 
     */
    public void setPremiumAmountPerSecurity(String value) {
        this.premiumAmountPerSecurity = value;
    }

}
