//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AuditorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuditorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NameOfAuditFirm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RegistrationNumberOfAuditFirm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NameOfAuditor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MembershipNumberOfAuditor" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="FinancialYearForWhichAppointed" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuditorType", propOrder = {
    "nameOfAuditFirm",
    "registrationNumberOfAuditFirm",
    "nameOfAuditor",
    "membershipNumberOfAuditor",
    "financialYearForWhichAppointed"
})
public class AuditorType {

    @XmlElement(name = "NameOfAuditFirm", required = true)
    protected String nameOfAuditFirm;
    @XmlElement(name = "RegistrationNumberOfAuditFirm", required = true)
    protected String registrationNumberOfAuditFirm;
    @XmlElement(name = "NameOfAuditor", required = true)
    protected String nameOfAuditor;
    @XmlElement(name = "MembershipNumberOfAuditor")
    protected int membershipNumberOfAuditor;
    @XmlElement(name = "FinancialYearForWhichAppointed", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar financialYearForWhichAppointed;

    /**
     * Gets the value of the nameOfAuditFirm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfAuditFirm() {
        return nameOfAuditFirm;
    }

    /**
     * Sets the value of the nameOfAuditFirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfAuditFirm(String value) {
        this.nameOfAuditFirm = value;
    }

    /**
     * Gets the value of the registrationNumberOfAuditFirm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumberOfAuditFirm() {
        return registrationNumberOfAuditFirm;
    }

    /**
     * Sets the value of the registrationNumberOfAuditFirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumberOfAuditFirm(String value) {
        this.registrationNumberOfAuditFirm = value;
    }

    /**
     * Gets the value of the nameOfAuditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfAuditor() {
        return nameOfAuditor;
    }

    /**
     * Sets the value of the nameOfAuditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfAuditor(String value) {
        this.nameOfAuditor = value;
    }

    /**
     * Gets the value of the membershipNumberOfAuditor property.
     * 
     */
    public int getMembershipNumberOfAuditor() {
        return membershipNumberOfAuditor;
    }

    /**
     * Sets the value of the membershipNumberOfAuditor property.
     * 
     */
    public void setMembershipNumberOfAuditor(int value) {
        this.membershipNumberOfAuditor = value;
    }

    /**
     * Gets the value of the financialYearForWhichAppointed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFinancialYearForWhichAppointed() {
        return financialYearForWhichAppointed;
    }

    /**
     * Sets the value of the financialYearForWhichAppointed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFinancialYearForWhichAppointed(XMLGregorianCalendar value) {
        this.financialYearForWhichAppointed = value;
    }

}
