//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ChargeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChargeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChargeHolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChargeID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AssetsCharged" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DateOfCreation" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DateOfModification" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DateOfSatisfaction" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ChargeAmount" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChargeType", propOrder = {
    "chargeHolder",
    "chargeID",
    "assetsCharged",
    "dateOfCreation",
    "dateOfModification",
    "dateOfSatisfaction",
    "chargeAmount"
})
public class ChargeType {

    @XmlElement(name = "ChargeHolder", required = true)
    protected String chargeHolder;
    @XmlElement(name = "ChargeID")
    protected int chargeID;
    @XmlElement(name = "AssetsCharged", required = true)
    protected String assetsCharged;
    @XmlElement(name = "DateOfCreation", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfCreation;
    @XmlElement(name = "DateOfModification", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfModification;
    @XmlElement(name = "DateOfSatisfaction", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfSatisfaction;
    @XmlElement(name = "ChargeAmount")
    protected String chargeAmount;

    /**
     * Gets the value of the chargeHolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeHolder() {
        return chargeHolder;
    }

    /**
     * Sets the value of the chargeHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeHolder(String value) {
        this.chargeHolder = value;
    }

    /**
     * Gets the value of the chargeID property.
     * 
     */
    public int getChargeID() {
        return chargeID;
    }

    /**
     * Sets the value of the chargeID property.
     * 
     */
    public void setChargeID(int value) {
        this.chargeID = value;
    }

    /**
     * Gets the value of the assetsCharged property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetsCharged() {
        return assetsCharged;
    }

    /**
     * Sets the value of the assetsCharged property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetsCharged(String value) {
        this.assetsCharged = value;
    }

    /**
     * Gets the value of the dateOfCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfCreation() {
        return dateOfCreation;
    }

    /**
     * Sets the value of the dateOfCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfCreation(XMLGregorianCalendar value) {
        this.dateOfCreation = value;
    }

    /**
     * Gets the value of the dateOfModification property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfModification() {
        return dateOfModification;
    }

    /**
     * Sets the value of the dateOfModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfModification(XMLGregorianCalendar value) {
        this.dateOfModification = value;
    }

    /**
     * Gets the value of the dateOfSatisfaction property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfSatisfaction() {
        return dateOfSatisfaction;
    }

    /**
     * Sets the value of the dateOfSatisfaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfSatisfaction(XMLGregorianCalendar value) {
        this.dateOfSatisfaction = value;
    }

    /**
     * Gets the value of the chargeAmount property.
     * 
     */
    public String getChargeAmount() {
        return chargeAmount;
    }

    /**
     * Sets the value of the chargeAmount property.
     * 
     */
    public void setChargeAmount(String value) {
        this.chargeAmount = value;
    }

}
