//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComputerEquipmentsMemberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComputerEquipmentsMemberType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OwnedAssetsMember" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComputerEquipmentsMemberType", propOrder = {
    "ownedAssetsMember"
})
public class ComputerEquipmentsMemberType {

    @XmlElement(name = "OwnedAssetsMember")
    protected String ownedAssetsMember;

    /**
     * Gets the value of the ownedAssetsMember property.
     * 
     */
    public String getOwnedAssetsMember() {
        return ownedAssetsMember;
    }

    /**
     * Sets the value of the ownedAssetsMember property.
     * 
     */
    public void setOwnedAssetsMember(String value) {
        this.ownedAssetsMember = value;
    }

}
