//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EmploymentDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmploymentDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NoOfEstablishments" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="NoOfEmployees" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *         &lt;element name="AmountOfPFPaid" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DataAsOf" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmploymentDetailsType", propOrder = {
    "noOfEstablishments",
    "noOfEmployees",
    "amountOfPFPaid"
})
public class EmploymentDetailsType {

    @XmlElement(name = "NoOfEstablishments")
    protected String noOfEstablishments;
    @XmlElement(name = "NoOfEmployees")
    protected String noOfEmployees;
    @XmlElement(name = "AmountOfPFPaid")
    protected String amountOfPFPaid;
    @XmlAttribute(name = "DataAsOf")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataAsOf;

    /**
     * Gets the value of the noOfEstablishments property.
     * 
     */
    public String getNoOfEstablishments() {
        return noOfEstablishments;
    }

    /**
     * Sets the value of the noOfEstablishments property.
     * 
     */
    public void setNoOfEstablishments(String value) {
        this.noOfEstablishments = value;
    }

    /**
     * Gets the value of the noOfEmployees property.
     * 
     */
    public String getNoOfEmployees() {
        return noOfEmployees;
    }

    /**
     * Sets the value of the noOfEmployees property.
     * 
     */
    public void setNoOfEmployees(String value) {
        this.noOfEmployees = value;
    }

    /**
     * Gets the value of the amountOfPFPaid property.
     * 
     */
    public String getAmountOfPFPaid() {
        return amountOfPFPaid;
    }

    /**
     * Sets the value of the amountOfPFPaid property.
     * 
     */
    public void setAmountOfPFPaid(String value) {
        this.amountOfPFPaid = value;
    }

    /**
     * Gets the value of the dataAsOf property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataAsOf() {
        return dataAsOf;
    }

    /**
     * Sets the value of the dataAsOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataAsOf(XMLGregorianCalendar value) {
        this.dataAsOf = value;
    }

}
