//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndividualForeignNationalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualForeignNationalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NoOfEquityShares" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PercentageOfEquityShares" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualForeignNationalType", propOrder = {
    "noOfEquityShares",
    "percentageOfEquityShares"
})
public class IndividualForeignNationalType {

    @XmlElement(name = "NoOfEquityShares", required = true)
    protected String noOfEquityShares;
    @XmlElement(name = "PercentageOfEquityShares", required = true)
    protected String percentageOfEquityShares;

    /**
     * Gets the value of the noOfEquityShares property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfEquityShares() {
        return noOfEquityShares;
    }

    /**
     * Sets the value of the noOfEquityShares property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfEquityShares(String value) {
        this.noOfEquityShares = value;
    }

    /**
     * Gets the value of the percentageOfEquityShares property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentageOfEquityShares() {
        return percentageOfEquityShares;
    }

    /**
     * Sets the value of the percentageOfEquityShares property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentageOfEquityShares(String value) {
        this.percentageOfEquityShares = value;
    }

}
