//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PrincipalProductOrServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrincipalProductOrServicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductOrService" type="{}ProductOrServiceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DataAsOf" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrincipalProductOrServicesType", propOrder = {
    "dataAsOf","productOrServiceList"
})
public class PrincipalProductOrServicesType {

/*    @XmlElement(name = "ProductOrService", required = false)
    protected ProductOrServiceType productOrService;*/
    @XmlAttribute(name = "DataAsOf", required = false)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataAsOf;

    @XmlElement(name = "ProductOrService", required = false)
    protected List<ProductOrServiceType> productOrServiceList;

    /**
     * Gets the value of the productOrService property.
     * 
     * @return
     *     possible object is
     *     {@link ProductOrServiceType }
     *     
     */
/*    public ProductOrServiceType getProductOrService() {
        return productOrService;
    }*/

    /**
     * Sets the value of the productOrService property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductOrServiceType }
     *     
     */
/*    public void setProductOrService(ProductOrServiceType value) {
        this.productOrService = value;
    }*/

    /**
     * Gets the value of the dataAsOf property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataAsOf() {
        return dataAsOf;
    }

    /**
     * Sets the value of the dataAsOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataAsOf(XMLGregorianCalendar value) {
        this.dataAsOf = value;
    }

//--- List type Product Service we will get this --//    
    public List<ProductOrServiceType> getProductOrService() {
        if (productOrServiceList == null) {
        	productOrServiceList = new ArrayList<ProductOrServiceType>();
        }
        return this.productOrServiceList;
    }
    
}
