//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShareCapitalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShareCapitalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EquityShareCapital" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreferenceShareCapital" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShareCapitalType", propOrder = {
    "equityShareCapital",
    "preferenceShareCapital"
})
public class ShareCapitalType {

    @XmlElement(name = "EquityShareCapital", required = true)
    protected EquityShareCapital equityShareCapital;
    @XmlElement(name = "PreferenceShareCapital", required = true)
    protected String preferenceShareCapital;

    /**
     * Gets the value of the equityShareCapital property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public EquityShareCapital getEquityShareCapital() {
        return equityShareCapital;
    }

    /**
     * Sets the value of the equityShareCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquityShareCapital(EquityShareCapital value) {
        this.equityShareCapital = value;
    }

    /**
     * Gets the value of the preferenceShareCapital property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferenceShareCapital() {
        return preferenceShareCapital;
    }

    /**
     * Sets the value of the preferenceShareCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferenceShareCapital(String value) {
        this.preferenceShareCapital = value;
    }

}
