//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.report.zauba.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StockExchangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StockExchangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StockExchangeCode" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="StockExchangeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StockExchangeType", propOrder = {
    "stockExchangeCode",
    "stockExchangeDescription"
})
public class StockExchangeType {

    @XmlElement(name = "StockExchangeCode")
    protected short stockExchangeCode;
    @XmlElement(name = "StockExchangeDescription", required = true)
    protected String stockExchangeDescription;

    /**
     * Gets the value of the stockExchangeCode property.
     * 
     */
    public short getStockExchangeCode() {
        return stockExchangeCode;
    }

    /**
     * Sets the value of the stockExchangeCode property.
     * 
     */
    public void setStockExchangeCode(short value) {
        this.stockExchangeCode = value;
    }

    /**
     * Gets the value of the stockExchangeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockExchangeDescription() {
        return stockExchangeDescription;
    }

    /**
     * Sets the value of the stockExchangeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockExchangeDescription(String value) {
        this.stockExchangeDescription = value;
    }

}
