//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.model.bir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CompanyProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreviousNames" type="{}PreviousNamesType"/>
 *         &lt;element name="PreviousCIN" type="{}PreviousCINType"/>
 *         &lt;element name="PAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Telephone" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DateOfIncorporation" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AuthorizedCapital" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PaidUpCapital" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="EmploymentDetails" type="{}EmploymentDetailsType"/>
 *         &lt;element name="EmailID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TypeOfCompany" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CategoryOfCompany" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubCategoryOfCompany" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StockExchangeDetails" type="{}StockExchangeDetailsType"/>
 *         &lt;element name="RegistrarAndTransferAgent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DataAsOf" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyProfileType", propOrder = {
    "cin",
    "name",
    "address",
    "previousNames",
    "previousCIN",
    "pan",
    "telephone",
    "dateOfIncorporation",
    "authorizedCapital",
    "paidUpCapital",
    "employmentDetails",
    "emailID",
    "typeOfCompany",
    "categoryOfCompany",
    "subCategoryOfCompany",
    "stockExchangeDetails",
    "registrarAndTransferAgent"
})
public class CompanyProfileType {

    @XmlElement(name = "CIN", required = true)
    protected String cin;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Address", required = true)
    protected String address;    //-------------New Element Added------------------------//
    @XmlElement(name = "PreviousNames", required = true)
    protected PreviousNamesType previousNames;
	@XmlElement(name = "PreviousCIN", required = true)
    protected PreviousCINType previousCIN;
    @XmlElement(name = "PAN", required = true)
    protected String pan;
    @XmlElement(name = "Telephone")
    protected int telephone;
    @XmlElement(name = "DateOfIncorporation", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfIncorporation;
    @XmlElement(name = "AuthorizedCapital")
    protected String authorizedCapital;
    @XmlElement(name = "PaidUpCapital")
    protected String paidUpCapital;
    @XmlElement(name = "EmploymentDetails", required = true)
    protected EmploymentDetailsType employmentDetails;
    @XmlElement(name = "EmailID", required = true)
    protected String emailID;
    @XmlElement(name = "TypeOfCompany", required = true)
    protected String typeOfCompany;
    @XmlElement(name = "CategoryOfCompany", required = true)
    protected String categoryOfCompany;
    @XmlElement(name = "SubCategoryOfCompany", required = true)
    protected String subCategoryOfCompany;
    @XmlElement(name = "StockExchangeDetails", required = true)
    protected StockExchangeDetailsType stockExchangeDetails;
    @XmlElement(name = "RegistrarAndTransferAgent", required = true)
    protected String registrarAndTransferAgent;
    @XmlAttribute(name = "DataAsOf")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataAsOf;

    public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
    
    /**
     * Gets the value of the cin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIN() {
        return cin;
    }

    /**
     * Sets the value of the cin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIN(String value) {
        this.cin = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the previousNames property.
     * 
     * @return
     *     possible object is
     *     {@link PreviousNamesType }
     *     
     */
    public PreviousNamesType getPreviousNames() {
        return previousNames;
    }

    /**
     * Sets the value of the previousNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviousNamesType }
     *     
     */
    public void setPreviousNames(PreviousNamesType value) {
        this.previousNames = value;
    }

    /**
     * Gets the value of the previousCIN property.
     * 
     * @return
     *     possible object is
     *     {@link PreviousCINType }
     *     
     */
    public PreviousCINType getPreviousCIN() {
        return previousCIN;
    }

    /**
     * Sets the value of the previousCIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviousCINType }
     *     
     */
    public void setPreviousCIN(PreviousCINType value) {
        this.previousCIN = value;
    }

    /**
     * Gets the value of the pan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAN() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAN(String value) {
        this.pan = value;
    }

    /**
     * Gets the value of the telephone property.
     * 
     */
    public int getTelephone() {
        return telephone;
    }

    /**
     * Sets the value of the telephone property.
     * 
     */
    public void setTelephone(int value) {
        this.telephone = value;
    }

    /**
     * Gets the value of the dateOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfIncorporation() {
        return dateOfIncorporation;
    }

    /**
     * Sets the value of the dateOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfIncorporation(XMLGregorianCalendar value) {
        this.dateOfIncorporation = value;
    }

    /**
     * Gets the value of the authorizedCapital property.
     * 
     */
    public String getAuthorizedCapital() {
        return authorizedCapital;
    }

    /**
     * Sets the value of the authorizedCapital property.
     * 
     */
    public void setAuthorizedCapital(String value) {
        this.authorizedCapital = value;
    }

    /**
     * Gets the value of the paidUpCapital property.
     * 
     */
    public String getPaidUpCapital() {
        return paidUpCapital;
    }

    /**
     * Sets the value of the paidUpCapital property.
     * 
     */
    public void setPaidUpCapital(String value) {
        this.paidUpCapital = value;
    }

    /**
     * Gets the value of the employmentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentDetailsType }
     *     
     */
    public EmploymentDetailsType getEmploymentDetails() {
        return employmentDetails;
    }

    /**
     * Sets the value of the employmentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentDetailsType }
     *     
     */
    public void setEmploymentDetails(EmploymentDetailsType value) {
        this.employmentDetails = value;
    }

    /**
     * Gets the value of the emailID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailID() {
        return emailID;
    }

    /**
     * Sets the value of the emailID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailID(String value) {
        this.emailID = value;
    }

    /**
     * Gets the value of the typeOfCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfCompany() {
        return typeOfCompany;
    }

    /**
     * Sets the value of the typeOfCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfCompany(String value) {
        this.typeOfCompany = value;
    }

    /**
     * Gets the value of the categoryOfCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryOfCompany() {
        return categoryOfCompany;
    }

    /**
     * Sets the value of the categoryOfCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryOfCompany(String value) {
        this.categoryOfCompany = value;
    }

    /**
     * Gets the value of the subCategoryOfCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCategoryOfCompany() {
        return subCategoryOfCompany;
    }

    /**
     * Sets the value of the subCategoryOfCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCategoryOfCompany(String value) {
        this.subCategoryOfCompany = value;
    }

    /**
     * Gets the value of the stockExchangeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link StockExchangeDetailsType }
     *     
     */
    public StockExchangeDetailsType getStockExchangeDetails() {
        return stockExchangeDetails;
    }

    /**
     * Sets the value of the stockExchangeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockExchangeDetailsType }
     *     
     */
    public void setStockExchangeDetails(StockExchangeDetailsType value) {
        this.stockExchangeDetails = value;
    }

    /**
     * Gets the value of the registrarAndTransferAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrarAndTransferAgent() {
        return registrarAndTransferAgent;
    }

    /**
     * Sets the value of the registrarAndTransferAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrarAndTransferAgent(String value) {
        this.registrarAndTransferAgent = value;
    }

    /**
     * Gets the value of the dataAsOf property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataAsOf() {
        return dataAsOf;
    }

    /**
     * Sets the value of the dataAsOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataAsOf(XMLGregorianCalendar value) {
        this.dataAsOf = value;
    }

}
