//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.model.bir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LawsuitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LawsuitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="District" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Court" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CaseYear" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="CaseNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CaseType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Petitioner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Respondent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LawsuitType", propOrder = {
    "state",
    "district",
    "court",
    "caseYear",
    "caseNo",
    "caseType",
    "petitioner",
    "respondent"
})
public class LawsuitType {

    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "District", required = true)
    protected String district;
    @XmlElement(name = "Court", required = true)
    protected String court;
    @XmlElement(name = "CaseYear")
    protected short caseYear;
    @XmlElement(name = "CaseNo")
    protected int caseNo;
    @XmlElement(name = "CaseType", required = true)
    protected String caseType;
    @XmlElement(name = "Petitioner", required = true)
    protected String petitioner;
    @XmlElement(name = "Respondent", required = true)
    protected String respondent;

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the court property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourt() {
        return court;
    }

    /**
     * Sets the value of the court property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourt(String value) {
        this.court = value;
    }

    /**
     * Gets the value of the caseYear property.
     * 
     */
    public short getCaseYear() {
        return caseYear;
    }

    /**
     * Sets the value of the caseYear property.
     * 
     */
    public void setCaseYear(short value) {
        this.caseYear = value;
    }

    /**
     * Gets the value of the caseNo property.
     * 
     */
    public int getCaseNo() {
        return caseNo;
    }

    /**
     * Sets the value of the caseNo property.
     * 
     */
    public void setCaseNo(int value) {
        this.caseNo = value;
    }

    /**
     * Gets the value of the caseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * Sets the value of the caseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseType(String value) {
        this.caseType = value;
    }

    /**
     * Gets the value of the petitioner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPetitioner() {
        return petitioner;
    }

    /**
     * Sets the value of the petitioner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPetitioner(String value) {
        this.petitioner = value;
    }

    /**
     * Gets the value of the respondent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespondent() {
        return respondent;
    }

    /**
     * Sets the value of the respondent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespondent(String value) {
        this.respondent = value;
    }

}
