//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.model.bir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NonPromotersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NonPromotersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndividualIndian" type="{}IndividualIndianType"/>
 *         &lt;element name="IndividualNRI" type="{}IndividualNRIType"/>
 *         &lt;element name="IndividualForeignNational" type="{}IndividualForeignNationalType"/>
 *         &lt;element name="CentralGovernment" type="{}CentralGovernmentType"/>
 *         &lt;element name="StateGovernment" type="{}StateGovernmentType"/>
 *         &lt;element name="GovernmentCompanies" type="{}GovernmentCompaniesType"/>
 *         &lt;element name="InsuranceCompanies" type="{}InsuranceCompaniesType"/>
 *         &lt;element name="Banks" type="{}BanksType"/>
 *         &lt;element name="FinancialInstitutions" type="{}FinancialInstitutionsType"/>
 *         &lt;element name="ForeignInstitutionalInvestors" type="{}ForeignInstitutionalInvestorsType"/>
 *         &lt;element name="MutualFunds" type="{}MutualFundsType"/>
 *         &lt;element name="VentureCapital" type="{}VentureCapitalType"/>
 *         &lt;element name="BodyCorporate" type="{}BodyCorporateType"/>
 *         &lt;element name="Others" type="{}OthersType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonPromotersType", propOrder = {
    "individualIndian",
    "individualNRI",
    "individualForeignNational",
    "centralGovernment",
    "stateGovernment",
    "governmentCompanies",
    "insuranceCompanies",
    "banks",
    "financialInstitutions",
    "foreignInstitutionalInvestors",
    "mutualFunds",
    "ventureCapital",
    "bodyCorporate",
    "others"
})
public class NonPromotersType {

    @XmlElement(name = "IndividualIndian", required = true)
    protected IndividualIndianType individualIndian;
    @XmlElement(name = "IndividualNRI", required = true)
    protected IndividualNRIType individualNRI;
    @XmlElement(name = "IndividualForeignNational", required = true)
    protected IndividualForeignNationalType individualForeignNational;
    @XmlElement(name = "CentralGovernment", required = true)
    protected CentralGovernmentType centralGovernment;
    @XmlElement(name = "StateGovernment", required = true)
    protected StateGovernmentType stateGovernment;
    @XmlElement(name = "GovernmentCompanies", required = true)
    protected GovernmentCompaniesType governmentCompanies;
    @XmlElement(name = "InsuranceCompanies", required = true)
    protected InsuranceCompaniesType insuranceCompanies;
    @XmlElement(name = "Banks", required = true)
    protected BanksType banks;
    @XmlElement(name = "FinancialInstitutions", required = true)
    protected FinancialInstitutionsType financialInstitutions;
    @XmlElement(name = "ForeignInstitutionalInvestors", required = true)
    protected ForeignInstitutionalInvestorsType foreignInstitutionalInvestors;
    @XmlElement(name = "MutualFunds", required = true)
    protected MutualFundsType mutualFunds;
    @XmlElement(name = "VentureCapital", required = true)
    protected VentureCapitalType ventureCapital;
    @XmlElement(name = "BodyCorporate", required = true)
    protected BodyCorporateType bodyCorporate;
    @XmlElement(name = "Others", required = true)
    protected OthersType others;

    /**
     * Gets the value of the individualIndian property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualIndianType }
     *     
     */
    public IndividualIndianType getIndividualIndian() {
        return individualIndian;
    }

    /**
     * Sets the value of the individualIndian property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualIndianType }
     *     
     */
    public void setIndividualIndian(IndividualIndianType value) {
        this.individualIndian = value;
    }

    /**
     * Gets the value of the individualNRI property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualNRIType }
     *     
     */
    public IndividualNRIType getIndividualNRI() {
        return individualNRI;
    }

    /**
     * Sets the value of the individualNRI property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualNRIType }
     *     
     */
    public void setIndividualNRI(IndividualNRIType value) {
        this.individualNRI = value;
    }

    /**
     * Gets the value of the individualForeignNational property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualForeignNationalType }
     *     
     */
    public IndividualForeignNationalType getIndividualForeignNational() {
        return individualForeignNational;
    }

    /**
     * Sets the value of the individualForeignNational property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualForeignNationalType }
     *     
     */
    public void setIndividualForeignNational(IndividualForeignNationalType value) {
        this.individualForeignNational = value;
    }

    /**
     * Gets the value of the centralGovernment property.
     * 
     * @return
     *     possible object is
     *     {@link CentralGovernmentType }
     *     
     */
    public CentralGovernmentType getCentralGovernment() {
        return centralGovernment;
    }

    /**
     * Sets the value of the centralGovernment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CentralGovernmentType }
     *     
     */
    public void setCentralGovernment(CentralGovernmentType value) {
        this.centralGovernment = value;
    }

    /**
     * Gets the value of the stateGovernment property.
     * 
     * @return
     *     possible object is
     *     {@link StateGovernmentType }
     *     
     */
    public StateGovernmentType getStateGovernment() {
        return stateGovernment;
    }

    /**
     * Sets the value of the stateGovernment property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateGovernmentType }
     *     
     */
    public void setStateGovernment(StateGovernmentType value) {
        this.stateGovernment = value;
    }

    /**
     * Gets the value of the governmentCompanies property.
     * 
     * @return
     *     possible object is
     *     {@link GovernmentCompaniesType }
     *     
     */
    public GovernmentCompaniesType getGovernmentCompanies() {
        return governmentCompanies;
    }

    /**
     * Sets the value of the governmentCompanies property.
     * 
     * @param value
     *     allowed object is
     *     {@link GovernmentCompaniesType }
     *     
     */
    public void setGovernmentCompanies(GovernmentCompaniesType value) {
        this.governmentCompanies = value;
    }

    /**
     * Gets the value of the insuranceCompanies property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceCompaniesType }
     *     
     */
    public InsuranceCompaniesType getInsuranceCompanies() {
        return insuranceCompanies;
    }

    /**
     * Sets the value of the insuranceCompanies property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceCompaniesType }
     *     
     */
    public void setInsuranceCompanies(InsuranceCompaniesType value) {
        this.insuranceCompanies = value;
    }

    /**
     * Gets the value of the banks property.
     * 
     * @return
     *     possible object is
     *     {@link BanksType }
     *     
     */
    public BanksType getBanks() {
        return banks;
    }

    /**
     * Sets the value of the banks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BanksType }
     *     
     */
    public void setBanks(BanksType value) {
        this.banks = value;
    }

    /**
     * Gets the value of the financialInstitutions property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialInstitutionsType }
     *     
     */
    public FinancialInstitutionsType getFinancialInstitutions() {
        return financialInstitutions;
    }

    /**
     * Sets the value of the financialInstitutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialInstitutionsType }
     *     
     */
    public void setFinancialInstitutions(FinancialInstitutionsType value) {
        this.financialInstitutions = value;
    }

    /**
     * Gets the value of the foreignInstitutionalInvestors property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignInstitutionalInvestorsType }
     *     
     */
    public ForeignInstitutionalInvestorsType getForeignInstitutionalInvestors() {
        return foreignInstitutionalInvestors;
    }

    /**
     * Sets the value of the foreignInstitutionalInvestors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignInstitutionalInvestorsType }
     *     
     */
    public void setForeignInstitutionalInvestors(ForeignInstitutionalInvestorsType value) {
        this.foreignInstitutionalInvestors = value;
    }

    /**
     * Gets the value of the mutualFunds property.
     * 
     * @return
     *     possible object is
     *     {@link MutualFundsType }
     *     
     */
    public MutualFundsType getMutualFunds() {
        return mutualFunds;
    }

    /**
     * Sets the value of the mutualFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link MutualFundsType }
     *     
     */
    public void setMutualFunds(MutualFundsType value) {
        this.mutualFunds = value;
    }

    /**
     * Gets the value of the ventureCapital property.
     * 
     * @return
     *     possible object is
     *     {@link VentureCapitalType }
     *     
     */
    public VentureCapitalType getVentureCapital() {
        return ventureCapital;
    }

    /**
     * Sets the value of the ventureCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link VentureCapitalType }
     *     
     */
    public void setVentureCapital(VentureCapitalType value) {
        this.ventureCapital = value;
    }

    /**
     * Gets the value of the bodyCorporate property.
     * 
     * @return
     *     possible object is
     *     {@link BodyCorporateType }
     *     
     */
    public BodyCorporateType getBodyCorporate() {
        return bodyCorporate;
    }

    /**
     * Sets the value of the bodyCorporate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyCorporateType }
     *     
     */
    public void setBodyCorporate(BodyCorporateType value) {
        this.bodyCorporate = value;
    }

    /**
     * Gets the value of the others property.
     * 
     * @return
     *     possible object is
     *     {@link OthersType }
     *     
     */
    public OthersType getOthers() {
        return others;
    }

    /**
     * Sets the value of the others property.
     * 
     * @param value
     *     allowed object is
     *     {@link OthersType }
     *     
     */
    public void setOthers(OthersType value) {
        this.others = value;
    }

}
