//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 07:58:31 PM IST 
//


package com.eir.model.bir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductOrServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductOrServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductOrServiceDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ITCCode" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ContributionToRevenue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductOrServiceType", propOrder = {
    "productOrServiceDescription",
    "itcCode",
    "contributionToRevenue"
})
public class ProductOrServiceType {

    @XmlElement(name = "ProductOrServiceDescription", required = false)
    protected String productOrServiceDescription;
    @XmlElement(name = "ITCCode", required = false)
    protected float itcCode;
    @XmlElement(name = "ContributionToRevenue", required = false)
    protected float contributionToRevenue;

    /**
     * Gets the value of the productOrServiceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductOrServiceDescription() {
        return productOrServiceDescription;
    }

    /**
     * Sets the value of the productOrServiceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductOrServiceDescription(String value) {
        this.productOrServiceDescription = value;
    }

    /**
     * Gets the value of the itcCode property.
     * 
     */
    public float getITCCode() {
        return itcCode;
    }

    /**
     * Sets the value of the itcCode property.
     * 
     */
    public void setITCCode(float value) {
        this.itcCode = value;
    }

    /**
     * Gets the value of the contributionToRevenue property.
     * 
     */
    public float getContributionToRevenue() {
        return contributionToRevenue;
    }

    /**
     * Sets the value of the contributionToRevenue property.
     * 
     */
    public void setContributionToRevenue(float value) {
        this.contributionToRevenue = value;
    }

}
