//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.08 at 06:13:32 PM IST 
//


package com.eir.report.nextgen.service.model.product;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdminSrch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdminSrch">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EperianReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IDNumberSearch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdminSrch", propOrder = {
    "eperianReferenceNumber",
    "idNumberSearch"
})
public class AdminSrch {

    @XmlElement(name = "EperianReferenceNumber", required = true)
    protected String eperianReferenceNumber;
    @XmlElement(name = "IDNumberSearch", required = true)
    protected String idNumberSearch;

    /**
     * Gets the value of the eperianReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEperianReferenceNumber() {
        return eperianReferenceNumber;
    }

    /**
     * Sets the value of the eperianReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEperianReferenceNumber(String value) {
        this.eperianReferenceNumber = value;
    }

    /**
     * Gets the value of the idNumberSearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNumberSearch() {
        return idNumberSearch;
    }

    /**
     * Sets the value of the idNumberSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNumberSearch(String value) {
        this.idNumberSearch = value;
    }

}
