//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.08 at 06:13:32 PM IST 
//


package com.eir.report.nextgen.service.model.product;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssignedProductList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssignedProductList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssignedProductList", propOrder = {
    "productCodeAndProductDescriptionAndProductName"
})
public class AssignedProductList {

    @XmlElementRefs({
        @XmlElementRef(name = "ProductCode", namespace = "http://experian.com/nextgen/schemas", type = JAXBElement.class),
        @XmlElementRef(name = "ProductDescription", namespace = "http://experian.com/nextgen/schemas", type = JAXBElement.class),
        @XmlElementRef(name = "ProductName", namespace = "http://experian.com/nextgen/schemas", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> productCodeAndProductDescriptionAndProductName;

    /**
     * Gets the value of the productCodeAndProductDescriptionAndProductName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productCodeAndProductDescriptionAndProductName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductCodeAndProductDescriptionAndProductName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getProductCodeAndProductDescriptionAndProductName() {
        if (productCodeAndProductDescriptionAndProductName == null) {
            productCodeAndProductDescriptionAndProductName = new ArrayList<JAXBElement<String>>();
        }
        return this.productCodeAndProductDescriptionAndProductName;
    }

}
