//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 08:04:36 PM IST 
//


package com.eir.report.nextgen.service.model.product;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.experian.nextgen.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.experian.nextgen.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdminSrch }
     * 
     */
    public AdminSrch createAdminSrch() {
        return new AdminSrch();
    }

    /**
     * Create an instance of {@link BusSrch }
     * 
     */
    public BusSrch createBusSrch() {
        return new BusSrch();
    }

    /**
     * Create an instance of {@link UserPref }
     * 
     */
    public UserPref createUserPref() {
        return new UserPref();
    }

    /**
     * Create an instance of {@link GetAssignedProductRequest }
     * 
     */
    public GetAssignedProductRequest createGetAssignedProductRequest() {
        return new GetAssignedProductRequest();
    }

    /**
     * Create an instance of {@link BusnesAcct }
     * 
     */
    public BusnesAcct createBusnesAcct() {
        return new BusnesAcct();
    }

    /**
     * Create an instance of {@link BinId }
     * 
     */
    public BinId createBinId() {
        return new BinId();
    }

    /**
     * Create an instance of {@link BusAddr }
     * 
     */
    public BusAddr createBusAddr() {
        return new BusAddr();
    }

    /**
     * Create an instance of {@link BusnPhone }
     * 
     */
    public BusnPhone createBusnPhone() {
        return new BusnPhone();
    }

    /**
     * Create an instance of {@link GetBusinessProductRequest }
     * 
     */
    public GetBusinessProductRequest createGetProductRequest() {
    	
    	GetBusinessProductRequest businessProductRequest = new GetBusinessProductRequest();
    	 
    	businessProductRequest.setSTARTENQ("START");
		EnqHeadr param = new EnqHeadr();
		param.setBureauMemberId("139");
		param.setPurpose("1");
		param.setProduct("INBCIR001");
		param.setSearchType("1");
		param.setEnquiryApplicationType("1");
		param.setEnquiryAccountType("010");
		param.setEnquiryAmount("32452");
		param.setFrequency("7");
		param.setClientEnquiryRefNumber("");
		param.setEnquiryAmtMonetaryType("");
		param.setDurationofAgrement("");
		businessProductRequest.setENQHEADR(param);
		UserPref userPref = new UserPref();
		userPref.setLanguage("ENG");
		businessProductRequest.setUSERPREF(userPref);
		
		List<BusSrch> busSrchArr = new ArrayList<BusSrch>();
		BusSrch busSrch = new BusSrch();
		busSrch.setBusName("Vivo Private Ltd");
		busSrch.setCompanyPan("AAAAR6643D");
		busSrchArr .add(busSrch);
		businessProductRequest.busnsrch = busSrchArr;
		
		List<BusAddr> busAddrArr = new ArrayList<>();
		BusAddr busAddr = new BusAddr();
		busAddr.setAddrType("14");
		busAddr.setCountryCode("IND");
		busAddr.setCity("MUMBAI");
		busAddr.setState("27");
		busAddr.setDistrict("");
		busAddr.setPINCode("400021");
		busAddr.setAddressLine1("NIK8th Floor Nike Building S.K.Marg WorliE");
		busAddr.setAddressLine2("");
		busAddr.setAddressLine3("");
		busAddrArr.add(busAddr);
		businessProductRequest.busnaddr = busAddrArr;

		businessProductRequest.setENDOFENQ("END");

		
		
        return businessProductRequest;
    }

    /**
     * Create an instance of {@link AddlProd }
     * 
     */
    public AddlProd createAddlProd() {
        return new AddlProd();
    }

    /**
     * Create an instance of {@link EnqHeadr }
     * 
     */
    public EnqHeadr createEnqHeadr() {
        return new EnqHeadr();
    }

}
