//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 08:04:36 PM IST 
//

/*@javax.xml.bind.annotation.XmlSchema(namespace = "http://experian.com/nextgen/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.experian.nextgen.ind.model.uif.shared.impl;
*/

@javax.xml.bind.annotation.XmlSchema(namespace = "http://experian.com/nextgen/schemas", 
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns = {
        @javax.xml.bind.annotation.XmlNs(prefix="sch", namespaceURI="http://experian.com/nextgen/schemas")
    })
package com.eir.report.nextgen.service.model.product;
import javax.xml.bind.annotation.*;