//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.14 at 07:31:34 AM CST 
//


package com.eir.report.nextgen.service.model.consumer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Employer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Employer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="occupationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="netMontlyIncome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="occYearsEmployed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="occMonthsEmployed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Employer", propOrder = {
    "occupationCode",
    "netMontlyIncome",
    "occYearsEmployed",
    "occMonthsEmployed"
})
public class Employer {

    @XmlElement(name="OccupationCode")
    protected String occupationCode;
    @XmlElement(name="NetMontlyIncome")
    protected String netMontlyIncome;
    @XmlElement(name="OccYearsEmployed")
    protected String occYearsEmployed;
    @XmlElement(name="OccMonthsEmployed")
    protected String occMonthsEmployed;

    /**
     * Gets the value of the occupationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationCode() {
        return occupationCode;
    }

    /**
     * Sets the value of the occupationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationCode(String value) {
        this.occupationCode = value;
    }

    /**
     * Gets the value of the netMontlyIncome property.
     * 
     */
    public String getNetMontlyIncome() {
        return netMontlyIncome;
    }

    /**
     * Sets the value of the netMontlyIncome property.
     * 
     */
    public void setNetMontlyIncome(String value) {
        this.netMontlyIncome = value;
    }

    /**
     * Gets the value of the occYearsEmployed property.
     * 
     */
    public String getOccYearsEmployed() {
        return occYearsEmployed;
    }

    /**
     * Sets the value of the occYearsEmployed property.
     * 
     */
    public void setOccYearsEmployed(String value) {
        this.occYearsEmployed = value;
    }

    /**
     * Gets the value of the occMonthsEmployed property.
     * 
     */
    public String getOccMonthsEmployed() {
        return occMonthsEmployed;
    }

    /**
     * Sets the value of the occMonthsEmployed property.
     * 
     */
    public void setOccMonthsEmployed(String value) {
        this.occMonthsEmployed = value;
    }

}
