//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.18 at 05:37:53 AM CST 
//


package com.eir.report.nextgen.service.model.consumer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnqHeadr complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnqHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientEnquiryRefNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bureauMemberId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="purposeOfInquiry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="purpose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="searchType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enquiryApplicationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enquiryAccountType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="enquiryAmtMonetaryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enquiryAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enquiryCreditPurpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="durationofAgreement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnqHeader", propOrder = {
    "clientEnquiryRefNumber",
    "bureauMemberId",
    "purposeOfInquiry",
    "purpose",
    "product",
    "searchType",
    "enquiryApplicationType",
    "enquiryAccountType",
    "enquiryAmtMonetaryType",
    "enquiryAmount",
    "enquiryCreditPurpose",
    "durationofAgreement",
    "frequency"
})
public class EnqHeader {

    @XmlElement(required = true,name="ClientEnquiryRefNumber")
    protected String clientEnquiryRefNumber;
    @XmlElement(required = true,name="BureauMemberId")
    protected String bureauMemberId;
    @XmlElement(name="PurposeOfInquiry")
    protected String purposeOfInquiry;
    @XmlElement(name="Purpose")
    protected String purpose;
    @XmlElement(name="Product")
    protected String product;
    @XmlElement(required = true,name="SearchType")
    protected String searchType;
    @XmlElement(required = true,name="EnquiryApplicationType")
    protected String enquiryApplicationType;
    @XmlElement(name="EnquiryAccountType")
    protected String enquiryAccountType;
    @XmlElement(required = true,name="EnquiryAmtMonetaryType")
    protected String enquiryAmtMonetaryType;
    @XmlElement(name="EnquiryAmount")
    protected String enquiryAmount;
    @XmlElement(required = true,name="EnquiryCreditPurpose")
    protected String enquiryCreditPurpose;
    @XmlElement(name="DurationofAgreement")
    protected String durationofAgreement;
    @XmlElement(name="Frequency")
    protected String frequency;

    /**
     * Gets the value of the clientEnquiryRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientEnquiryRefNumber() {
        return clientEnquiryRefNumber;
    }

    /**
     * Sets the value of the clientEnquiryRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientEnquiryRefNumber(String value) {
        this.clientEnquiryRefNumber = value;
    }

    /**
     * Gets the value of the bureauMemberId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauMemberId() {
        return bureauMemberId;
    }

    /**
     * Sets the value of the bureauMemberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauMemberId(String value) {
        this.bureauMemberId = value;
    }

    /**
     * Gets the value of the purposeOfInquiry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurposeOfInquiry() {
        return purposeOfInquiry;
    }

    /**
     * Sets the value of the purposeOfInquiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurposeOfInquiry(String value) {
        this.purposeOfInquiry = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the searchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchType() {
        return searchType;
    }

    /**
     * Sets the value of the searchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchType(String value) {
        this.searchType = value;
    }

    /**
     * Gets the value of the enquiryApplicationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnquiryApplicationType() {
        return enquiryApplicationType;
    }

    /**
     * Sets the value of the enquiryApplicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnquiryApplicationType(String value) {
        this.enquiryApplicationType = value;
    }

    /**
     * Gets the value of the enquiryAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnquiryAccountType() {
        return enquiryAccountType;
    }

    /**
     * Sets the value of the enquiryAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnquiryAccountType(String value) {
        this.enquiryAccountType = value;
    }

    /**
     * Gets the value of the enquiryAmtMonetaryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnquiryAmtMonetaryType() {
        return enquiryAmtMonetaryType;
    }

    /**
     * Sets the value of the enquiryAmtMonetaryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnquiryAmtMonetaryType(String value) {
        this.enquiryAmtMonetaryType = value;
    }

    /**
     * Gets the value of the enquiryAmount property.
     * 
     */
    public String getEnquiryAmount() {
        return enquiryAmount;
    }

    /**
     * Sets the value of the enquiryAmount property.
     * 
     */
    public void setEnquiryAmount(String value) {
        this.enquiryAmount = value;
    }

    /**
     * Gets the value of the enquiryCreditPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnquiryCreditPurpose() {
        return enquiryCreditPurpose;
    }

    /**
     * Sets the value of the enquiryCreditPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnquiryCreditPurpose(String value) {
        this.enquiryCreditPurpose = value;
    }

    /**
     * Gets the value of the durationofAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationofAgreement() {
        return durationofAgreement;
    }

    /**
     * Sets the value of the durationofAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationofAgreement(String value) {
        this.durationofAgreement = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

}
