//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.14 at 07:31:34 AM CST 
//


package com.eir.report.nextgen.service.model.consumer;

import javax.xml.bind.annotation.XmlRegistry;




/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.experian.nextgen.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.experian.nextgen.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnqHeader }
     * 
     */
    public EnqHeader createEnqHeader() {
        return new EnqHeader();
    }

    /**
     * Create an instance of {@link AddlProd }
     * 
     */
    public AddlProd createAddlProd() {
        return new AddlProd();
    }

    /**
     * Create an instance of {@link PinId }
     * 
     */
    public PinId createPinId() {
        return new PinId();
    }

    /**
     * Create an instance of {@link PersAddr }
     * 
     */
    public PersAddr createPersAddr() {
        return new PersAddr();
    }

    /**
     * Create an instance of {@link PersEmail }
     * 
     */
    public PersEmail createPersEmail() {
        return new PersEmail();
    }

    /**
     * Create an instance of {@link Employer }
     * 
     */
    public Employer createEmployer() {
        return new Employer();
    }

    /**
     * Create an instance of {@link UserPref }
     * 
     */
    public UserPref createUserPref() {
        return new UserPref();
    }

    /**
     * Create an instance of {@link PersPhone }
     * 
     */
    public PersPhone createPersPhone() {
        return new PersPhone();
    }

    /**
     * Create an instance of {@link PersAlias }
     * 
     */
    public PersAlias createPersAlias() {
        return new PersAlias();
    }

    /**
     * Create an instance of {@link PrsnSrch }
     * 
     */
    public PrsnSrch createPrsnSrch() {
        return new PrsnSrch();
    }

    /**
     * Create an instance of {@link PersonId }
     * 
     */
    public PersonId createPersonId() {
        return new PersonId();
    }

    /**
     * Create an instance of {@link GetConsumerProductRequest }
     * 
     */
    public GetConsumerProductRequest createGetConsumerProductRequest() {
        return new GetConsumerProductRequest();
    }

    /**
     * Create an instance of {@link PersonBnk }
     * 
     */
    public PersonBnk createPersonBnk() {
        return new PersonBnk();
    }
   
    /**
     * Create an instance of {@link PersDetail }
     * 
     */
    public PersDetail createPersDetail() {
        return new PersDetail();
    }

}
