//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.14 at 07:31:34 AM CST 
//


package com.eir.report.nextgen.service.model.consumer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersEmail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersEmail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="webAddrType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="webAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersEmail", propOrder = {
    "webAddrType",
    "webAddr"
})
public class PersEmail {

    @XmlElement(required = true,name="WebAddrType")
    protected String webAddrType;
    @XmlElement(required = true,name="WebAddr")
    protected String webAddr;

    /**
     * Gets the value of the webAddrType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebAddrType() {
        return webAddrType;
    }

    /**
     * Sets the value of the webAddrType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebAddrType(String value) {
        this.webAddrType = value;
    }

    /**
     * Gets the value of the webAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebAddr() {
        return webAddr;
    }

    /**
     * Sets the value of the webAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebAddr(String value) {
        this.webAddr = value;
    }

}
