//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.14 at 07:31:34 AM CST 
//


package com.eir.report.nextgen.service.model.consumer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numberOfCreditCardHeld" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maritalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="monthlyFamilyExpenseAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numberDependents" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="povertyIndex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetOwnershipIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersDetail", propOrder = {
    "numberOfCreditCardHeld",
    "maritalStatus",
    "monthlyFamilyExpenseAmt",
    "numberDependents",
    "povertyIndex",
    "assetOwnershipIndicator"
})
public class PersDetail {

	@XmlElement(name="NumberOfCreditCardHeld")
    protected String numberOfCreditCardHeld;
    @XmlElement(required = true,name="MaritalStatus")
    protected String maritalStatus;
    @XmlElement(name="MonthlyFamilyExpenseAmt")
    protected String monthlyFamilyExpenseAmt;
    @XmlElement(required = true,name="NumberDependents")
    protected String numberDependents;
    @XmlElement(required = true,name="PovertyIndex")
    protected String povertyIndex;
    @XmlElement(required = true,name="AssetOwnershipIndicator")
    protected String assetOwnershipIndicator;

    /**
     * Gets the value of the numberOfCreditCardHeld property.
     * 
     */
    public String getNumberOfCreditCardHeld() {
        return numberOfCreditCardHeld;
    }

    /**
     * Sets the value of the numberOfCreditCardHeld property.
     * 
     */
    public void setNumberOfCreditCardHeld(String value) {
        this.numberOfCreditCardHeld = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the monthlyFamilyExpenseAmt property.
     * 
     */
    public String getMonthlyFamilyExpenseAmt() {
        return monthlyFamilyExpenseAmt;
    }

    /**
     * Sets the value of the monthlyFamilyExpenseAmt property.
     * 
     */
    public void setMonthlyFamilyExpenseAmt(String value) {
        this.monthlyFamilyExpenseAmt = value;
    }

    /**
     * Gets the value of the numberDependents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberDependents() {
        return numberDependents;
    }

    /**
     * Sets the value of the numberDependents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberDependents(String value) {
        this.numberDependents = value;
    }

    /**
     * Gets the value of the povertyIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPovertyIndex() {
        return povertyIndex;
    }

    /**
     * Sets the value of the povertyIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPovertyIndex(String value) {
        this.povertyIndex = value;
    }

    /**
     * Gets the value of the assetOwnershipIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetOwnershipIndicator() {
        return assetOwnershipIndicator;
    }

    /**
     * Sets the value of the assetOwnershipIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetOwnershipIndicator(String value) {
        this.assetOwnershipIndicator = value;
    }

}
